// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWScE60jl4x0MJLxQdP7DuTfoQYKFczKQ',
    appId: '1:892818433986:web:7de26f1b4f48b0d0af185b',
    messagingSenderId: '892818433986',
    projectId: 'studybuddy-46578',
    authDomain: 'studybuddy-46578.firebaseapp.com',
    storageBucket: 'studybuddy-46578.firebasestorage.app',
    measurementId: 'G-BN11ZK6H8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3_sf0AebNfRPAqZzB51DktYOcXQENGRw',
    appId: '1:892818433986:android:4af19fd2eda5d807af185b',
    messagingSenderId: '892818433986',
    projectId: 'studybuddy-46578',
    storageBucket: 'studybuddy-46578.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDooGovz1JuUiP_ApgqR9ftfY5TNqgbOgs',
    appId: '1:892818433986:ios:6f4b853ee4fdf4abaf185b',
    messagingSenderId: '892818433986',
    projectId: 'studybuddy-46578',
    storageBucket: 'studybuddy-46578.firebasestorage.app',
    iosBundleId: 'com.example.studyBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDooGovz1JuUiP_ApgqR9ftfY5TNqgbOgs',
    appId: '1:892818433986:ios:6f4b853ee4fdf4abaf185b',
    messagingSenderId: '892818433986',
    projectId: 'studybuddy-46578',
    storageBucket: 'studybuddy-46578.firebasestorage.app',
    iosBundleId: 'com.example.studyBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWScE60jl4x0MJLxQdP7DuTfoQYKFczKQ',
    appId: '1:892818433986:web:ca63b2650f54e051af185b',
    messagingSenderId: '892818433986',
    projectId: 'studybuddy-46578',
    authDomain: 'studybuddy-46578.firebaseapp.com',
    storageBucket: 'studybuddy-46578.firebasestorage.app',
    measurementId: 'G-KG41J3T8JQ',
  );
}
